# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Azure-Infra_Pool

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: JFrogGenericArtifacts@1
  inputs:
    command: 'Download'
    connection: 'jfrogscv2'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
              "pattern": "rba-artifacts/spring-boot/spring-boot/2.6.9/spring-boot-2.6.9.jar",
                   "target": "rba-artifacts/"
          }
        ]
      }
      file: https://devopsrbapoc.jfrog.io/artifactory/devopsrbapoc-generic-local/sample.jar

- script: |
    echo pwd
- task: Docker@2
  displayName: build an image
  inputs:
    azureSubscriptionEndpoint: 7716be7b-283b-41a7-800e-30522542cc76
    azureContainerRegistry: '{"loginServer":"acr5000.azurecr.io", "id" : "/subscriptions/579ac225-23b7-4453-9785-6042f2570fe8/resourceGroups/Rg-tp-con-enw-cs-aue1/providers/Microsoft.ContainerRegistry/registries/ACR5000"}'
    dockerFile: Dockerfile





