jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: Azure-Infra_Pool
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: JFrogGenericArtifacts@1
    displayName: JFrog Generic Artifacts Download
    inputs:
      command: Download
      connection: 82b2c480-a07d-45b4-9441-294726466706
      fileSpec: >-
        {
          "files": [
            {
              "pattern": "rba-artifacts/spring-boot/spring-boot/2.6.9/spring-boot-2.6.9.jar",
              "target": "rba-artifacts/"
            }
          ]
        }
      file: https://devopsrbapoc.jfrog.io/artifactory/devopsrbapoc-generic-local/sample.jar
  - task: Docker@0
    displayName: build an image
    inputs:
      azureSubscriptionEndpoint: 7716be7b-283b-41a7-800e-30522542cc76
      azureContainerRegistry: '{"loginServer":"acr5000.azurecr.io", "id" : "/subscriptions/579ac225-23b7-4453-9785-6042f2570fe8/resourceGroups/Rg-tp-con-enw-cs-aue1/providers/Microsoft.ContainerRegistry/registries/ACR5000"}'
      dockerFile: Dockerfile
  - task: Docker@0
    displayName: Push an image
    inputs:
      azureSubscriptionEndpoint: 7716be7b-283b-41a7-800e-30522542cc76
      azureContainerRegistry: '{"loginServer":"acr5000.azurecr.io", "id" : "/subscriptions/579ac225-23b7-4453-9785-6042f2570fe8/resourceGroups/Rg-tp-con-enw-cs-aue1/providers/Microsoft.ContainerRegistry/registries/ACR5000"}'
      action: Push an image
      imageName: acr5000.azurecr.io/pasikantikarthik/mypythondockerrepo:$(Build.BuildId)
...
